env:
  browser: true
  es6: true
  node: true
extends:
  - eslint:recommended
  - plugin:import/errors
  - plugin:import/warnings
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
parser: 'babel-eslint'
plugins:
  - react
  - import
settings:
  pragma:
    - h
rules:
  indent:
    - error
    - 4
  linebreak-style:
    - 0
  quotes:
    - error
    - single
    - allowTemplateLiterals: true
  semi:
    - error
    - never
  no-console:
    - 0
  no-unused-vars:
    - 0
  import/no-unresolved: 0
